<a href="https://colab.research.google.com/github/JossRoss04/mineriaDeDatos/blob/main/mineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Míneria de Datos

## Primer parcial

### Introducción

#### Conceptos

**Mineria de Datos:** Es la recolección de datos implementando distintas estrategias y herramientas con el fin de excarvar sus patrones, llevandolas al analisis para la predicción y descripción de información.

#### Ciencia de Datos

In [ ]:
# La función help nos muestra la ayuda
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
# Otra forma de obtener ayuda es utilizando el caracter ?
len?

In [ ]:
# Así creamos una lista
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

Object `L` not found.


In [6]:
 # Ejemplo con una función con Docstring
 def square(a):
  """Return the square of a."""
  return a ** 2



In [7]:
square(5)

25

####IPython Magic Commands

#####Timing Code Execution:

In [1]:
#Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

The slowest run took 4.90 times longer than the fastest. This could mean that an intermediate result is being cached.
122 µs ± 88.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [2]:
#Con doble % podemos evaluar el desempeño de multiples lineas
%%timeit
L=[]
for n in range(1000):
  L.append(n**2)

93.8 µs ± 27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [3]:
!ls

sample_data


In [8]:
!pwd

/content


In [9]:
!echo

In [12]:
directory = !pwd

In [13]:
print(directory)

['/content']


In [14]:
%cd /content/

/content


In [15]:
%ls

sample_data/


####Understanding Data Types in Python

In [16]:
import numpy as np

In [17]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
np.array([3.14, 4, 2, 3], dtype='float32')

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [20]:
np.array([3.14, 4, 2, 3], dtype='int')

array([3, 4, 2, 3])

In [21]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i+3) for i in (2, 4, 6)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
[range(i, i+3) for i in [2, 3, 4]]


[range(2, 5), range(3, 6), range(4, 7)]